version: '3'
services:
  freeswitch:
    image: evgeniyklemin/freeswitch-mini:latest
    network_mode: host
    volumes:
      - ./conf:/etc/freeswitch
      - ./share:/usr/share/freeswitch
    tmpfs:
      - /var/lib/freeswitch/db
